version: "3.8"
services: 
  postgres:
    image: postgres
    container_name: pg-docker
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes: 
      - /data/postgres
