version: "3.8"
services: 
  postgres:
    image: postgres
    container_name: pg-docker
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /data/postgres
    volumes: 
      - '5432:5432'
    env_file:
      - .env.pg
    volumes:
